#   ______                        ______   __           
#  /      \                      /      \ |  \          
# |  $$$$$$\  ______   _______  |  $$$$$$\ \$$  ______  
# | $$   \$$ /      \ |       \ | $$_  \$$|  \ /      \ 
# | $$      |  $$$$$$\| $$$$$$$\| $$ \    | $$|  $$$$$$\
# | $$   __ | $$  | $$| $$  | $$| $$$$    | $$| $$  | $$
# | $$__/  \| $$__/ $$| $$  | $$| $$      | $$| $$__| $$
#  \$$    $$ \$$    $$| $$  | $$| $$      | $$ \$$    $$
#   \$$$$$$   \$$$$$$  \$$   \$$ \$$       \$$ _\$$$$$$$
#                                             |  \__| $$
#                                              \$$    $$
#                                               \$$$$$$ 
# Title: 程序运行配置
# Warning: 本程序仅供学习和参考，禁止用于商业或违法犯罪用途！

# 网课网站的账号信息
member: 
  # 账号
  user: xxx

  # 密码
  pass: xxx

# 视频任务自动评论
videoComment: false

# 视频评打分
videoStar: 5.0

# 自动评论列表
commentList:
  - 已学
  - 学到了

# 保存 Cookies
# 当登陆成功后，保存 Cookies 到本地，当下次运行时
# 若 Cookies 有效, 则使用 Cookies 进行登陆
saveCookies: false

# 【学小易】搜题App 的账号信息
store: 
  # 账号
  user: xxx

  # 密码
  pass: xxx